pipeline{
    agent any

    stages{
        stage('git-checkout'){
            steps{
                git branch: 'development', url: 'https://github.com/nehal-kadabi/nehaltollsfile.git'
            }
        }
    }
}
