pipeline {
    agent any  // This means it can run on any available agent
    
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/nehal-kadabi/nehaltollsfile.git'
            }
        }

        stage('Build') {
            steps {
                echo 'Building the project...'
            }
        }

        stage('Test') {
            steps {
                echo 'Running tests...'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying the project...'
            }
        }
    }
}
