pipeline{
    stages{
        stage('git-checkout'){
            steps{
                git branch: 'main', url: 'https://github.com/nehal-kadabi/nehaltollsfile.git'
            }
        }

        stage('compile'){
            steps{
                sh 'mvn compile'
            }
        }

        stage('Build'){
            steps{
                sh 'mvn clean package'
            }
        }

    }
}
